image: docker:latest

services:
  - docker:dind

before_script:
  - docker info

stages:
  - test
  - test_and_build_frontend
  - build_nginx

Test:
  stage: test

  script:
  - docker build -t node-container -f src/ensembl/Dockerfile.ci src/ensembl

  except:
    - test-cicd

Test and Build:
  stage: test_and_build_frontend

  script:
  - docker build -t node-container -f src/ensembl/Dockerfile.build .

  only:
    - test-cicd
